name: CI for ML.NET Fork

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      id: build
      run: |
        dotnet build --configuration Release --no-restore 2>&1 | Out-File -FilePath build_output.txt
        $LastExitCode | Out-File -FilePath build_exit_code.txt
      continue-on-error: true

    - name: Run tests
      id: test
      run: |
        dotnet test --configuration Release --no-build --logger "trx;LogFileName=test_results.trx" 2>&1 | Out-File -FilePath test_output.txt
        $LastExitCode | Out-File -FilePath test_exit_code.txt
      continue-on-error: true

    - name: Generate summary report
      run: |
        $reportFileName = "ci_summary_report.txt"
        
        Add-Content -Path $reportFileName -Value "--- CI Summary Report ---"
        
        # Check build status
        $buildExitCode = Get-Content build_exit_code.txt
        if ($buildExitCode -ne "0") {
            Add-Content -Path $reportFileName -Value "Build failed with exit code: $buildExitCode"
            Select-String -Path build_output.txt -Pattern 'error' | Out-File -FilePath -Append $reportFileName
        } else {
            Add-Content -Path $reportFileName -Value "Build: SUCCESS"
        }
        
        Add-Content -Path $reportFileName -Value ""
        
        # Check test status
        $testExitCode = Get-Content test_exit_code.txt
        if ($testExitCode -ne "0") {
            Add-Content -Path $reportFileName -Value "Tests failed with exit code: $testExitCode"
            Select-String -Path test_output.txt -Pattern 'Failed:' | Out-File -FilePath -Append $reportFileName
        } else {
            Add-Content -Path $reportFileName -Value "Tests: SUCCESS"
        }
        
        Add-Content -Path $reportFileName -Value ""
        Add-Content -Path $reportFileName -Value "For full logs, see build_output.txt, test_output.txt, and test_results.trx artifacts."

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ci-logs
        path: |
          ci_summary_report.txt
          build_output.txt
          test_output.txt
          test_results.trx
